### ISSUE TITLE
Develop automatic emails per CRP

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1035]
MARLO Automatic Emails: https://docs.google.com/document/d/1gchg7Rmd6IBspMGkzIL1MugKIM2mSjtSg4sRSgx3qnA/edit

**Comment by AndresFVR** [comment]
List of emails:

- [ ] EMAIL #1: Welcome to MARLO
- [ ] EMAIL #2: A new role has been assigned in the PMU
- [ ] EMAIL #3: A role has been removed in the PMU	
- [ ] EMAIL #4: A new role has been assigned as flagship leader	
- [ ] EMAIL #5: A flagship leader’s role has been removed	
- [ ] EMAIL #6: A new role as been assigned as cluster leader	
- [ ] EMAIL #7: A cluster leader’s role has been removed	
- [ ] EMAIL #8: A new role as been assigned as flagship manager	
- [ ] EMAIL #9: A flagship manager’s role has been removed	
- [ ] EMAIL #10 A new role has been assigned as project leader	
- [ ] EMAIL #11: A project leader’s role has been removed	
- [ ] EMAIL #12: A new role has been assigned as project coordinator	
- [ ] EMAIL #13: A project coordinator’s role has been removed	
- [ ] EMAIL #14: A flagship impact pathway has been submitted	
- [ ] EMAIL #15: A flagship impact pathway has been un-submitted	
- [ ] EMAIL #16: A project has been submitted by the project leader	
- [ ] EMAIL #17: A project has been returned to the project leader by the flagship/cluster leader	
- [ ] EMAIL #18: A project has been submitted by the flagship/cluster leader	
- [ ] EMAIL #19: A project has been returned to the project leader by the PMU

**Comment by htobon** [comment]
Hi @AndresFVR. Well done.
Please apply the following adjustments:

- [ ] Flagship leader removed
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-68478d4621a44d6b4c416aaebbc91dc35a5584829f6ce43ab13c13ab499d84cf.png)

- [ ]

**Comment by AndresFVR** [comment]
- [ ] Add Email to support message

**Comment by htobon** [comment]
@AndresFVR, @sebas932, if everything is fine, can you please release this improvement into the production environment?
