### ISSUE TITLE
Project locations revamp

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1298]
- [x] Change position of global/regional dimension questions
- [x] Develop other locations table
- [x] Develop adding a new location popup
- [x] Implement google maps in popup
- [x] Meet with David and Hector for getting feedback

**Comment by sebas932** [comment]
Moved to the next sprint

**Comment by jhanzuro** [comment]
![image](https://user-images.githubusercontent.com/30579639/36914960-0344d568-1e1d-11e8-8669-5419207fee14.png)
![image](https://user-images.githubusercontent.com/30579639/36915018-2b7918be-1e1d-11e8-819a-50dfee5d5274.png)

**Comment by jhanzuro** [comment]
Deployed in MARLO Testing environment
