### ISSUE TITLE
Project Highlights Annualization

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#1334]

**Comment by htobon** [comment]
- [ ] Tooltip issue
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/ae143384-534c-4b91-b52d-65facda45913)

- [ ] 2017 year only
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/28f66339-e110-43f8-93a7-9b45d5b36c64)

- [ ] Image is not uploading
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/479b547e-68b9-494f-8d34-ab4411178c65)

- [ ] Project highlight types did not save
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/b7263707-37f7-491a-8d88-ce7db3033d7c)

- [ ] Not all countries are being saved
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/8ac996ee-3f1f-4492-ab68-0e976bbd5d90)

- [ ] Getting oops after hitting the save button.
