### ISSUE TITLE
Project Description Rules Reporting

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#1346]
- [ ] Revisar que se reportan los proyectos activos en 2017
- [ ] A que fase siguiente se debe replicar la información?
- [ ] Revisar qué campos son editables en description?
- [ ] Revisar que vamos a hacer con el status

**Comment by mralmanzar** [comment]
This issue was resolved with the issue https://github.com/CCAFS/MARLO/issues/1015
