### ISSUE TITLE
Project Outcome Contribution Reporting Rules

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#1366]
- [x] Qué hacemos con "Further Flagship Contributions"
- [ ] Que hacemos con "Communications" en CRP Outcomes
- [ ] Que hacemos con "Nex Users" en CRP Outcomes
- [ ] Qué pasa si un proyecto dejó de contribuir a un Outcome/milestone
- [ ] Qué hacemos si el proyecto ha contribuido a un nuevo Outcome/milestone no planeado
