### ISSUE TITLE
Publication Annualization

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1409]

**Comment by AndresFVR** [comment]
Hi @sebas932 , could you please help me with the following tasks?
- [ ] Hide publications when a Planning phase is selected.
- [ ] Add Description field.
- [ ] Include No regional programmatic focus to the regions list.
- [ ] Review Regions and Flagships (Check validation is not working) 

Thank you :)

**Comment by AndresFVR** [comment]
Nuevos requerimientos: 

- [ ] Agregar nuevos campos para Patent y PVP (ver imagen abajo):
![image.png](https://images.zenhubusercontent.com/57fae24d95e42b6c5baa305d/22b909c0-0209-48fb-b739-708b5f4b39bd)

- [ ] Agregar campos para fechas.

**Comment by AndresFVR** [comment]
@HermesJim will do the permissions for publications:
- [ ] Institutions
- [ ] Flagships/Regions
- [ ] Created by
