### ISSUE TITLE
Add Control List SMO codes in MARLO

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1521]
Document: https://docs.google.com/spreadsheets/d/1Cg2LGETlPoKczm68Ond1spdvOPg2dTjJLgIW0PJ4qR0/edit#gid=1914557290

- [x] 1.1 SRF SLOs
- [x] 1.2 SRF IDOs
- [x] 1.3 SRF Cross-Cutting Issues 
- [x] 1.4 SRF Sub-IDOs
- [x] 1.5 SRF SLO Indicator Targets
- [x] SDGs
- [x] Geographic Scope: IATI standard
- [x] Regions: SMO Code, IATI 
- [x] Add new regions Ids on Control List document
- [x] Countries
- [x] Global Unit

**Comment by kenjitm** [comment]
Table srf_slo_indicator_targets:

![srfslotargetsindicators.PNG](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/890620d9-79eb-4384-94ad-7cbc7e5bb27b)
