### ISSUE TITLE
AR 2018 - Projects: LP6 

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#1658]

**Comment by htobon** [comment]
Feedback January 28th, 2019:

- [ ] PDF Link is not working
![image](https://user-images.githubusercontent.com/5375915/51847171-2087b600-22e9-11e9-9da5-a159359905b0.png)

- [ ] Exit icon in the popup is not very explicit
![image](https://user-images.githubusercontent.com/5375915/51847230-47de8300-22e9-11e9-819d-5ce808f962d9.png)

- [ ] Align text to left and justify
![image](https://user-images.githubusercontent.com/5375915/51847284-680e4200-22e9-11e9-86f9-7628f6afbb59.png)

- [ ] It is not clear what to do when one say that the project is contributing to LP6
![image](https://user-images.githubusercontent.com/5375915/51847513-d6530480-22e9-11e9-9e4b-58e63999cec7.png)

- [ ]

**Comment by htobon** [comment]
Feedback received by Ana Maria on January 30th, 2019:

- [ ] A pdf document is not necessary. The pop up box works well enough, but can we also have this box appear in the second page when respondents answer more questions?
- [ ] In the description we say, “LP6 is in charge of generating, translating and synthesizing climate change knowledge at the regional and global levels”, can we change this for the following: “LP6 is in charge of generating, translating and synthesizing climate change knowledge at the national, regional and global levels”
- [ ] Can we reword the following question: ‘Are you undertaking efforts to position CGIAR as the leading global research organization for food systems and climate change in developing countries?  Like this: Are you undertaking efforts to work with multiple CGIAR centres and research programs in order to position the CGIAR as the leading global research organization for food systems and climate change in developing countries? 
- [ ] Is it possible to set up the page so that if someone says Yes to Is this project contributing to Learning Platform 6?*, they automatically go to the next page? Currently one has to click on a link.
- [ ] Ana Maria: "estoy en la parte de Geographic scope: Qué pasa si uno tiene mas de uno? Es decir que yo quiera poner global pero Tambien regional. Se pueden tener diferentes iniciativas. Una puede ser regional y otra globa"

**Comment by AndresFVR** [comment]
Hola Hector,

Sobre los comentarios de Ana, ya se realizaron los primeros tres y se encuentra en marlo dev.

- [ ] 4. Sobre el cuarto, que piensas sobre este cambio? Pensamos que podría ser confuso para el usuario que se redirija a otra página.

- [ ] 5. Sobre el quinto, quedamos en que ibas a hablar con nosotros despues de una reunion para que definamos que vamos a realizar.
