### ISSUE TITLE
[MA] Table 5 - Milestones progress cube

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1951]
Create a cube that handles the milestones progress.
- [x] Design the new cube
- [x] Create the queries on MARLO
- [x] Create ELTs
- [x] Create 2018 cube document
- [x] Send the information to Snowflake

**Deliverable:** cube document and mail to Tania to use the cube.
**Move to Review when:** never
**Move to Closed when:** After mail to Tania. All possible errors will handle as a new ticket.

**Comment by mralmanzar** [comment]
the ETLs was delveloped and the mail was sended to Tania.
