### ISSUE TITLE
[MA] (MEL import)  outcomes and milestones status  on MARLO

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1984]
Create the MEL CRP/PTF  outcomes and milestones status on MARLO.

- [x] Send an Email requesting the information
- [x] Create 2018 planned Outcomes
- [x] Create AR 2018 planned outcomes status
- [x] Update the Dashboard information

**Deliverable:** Mail to team informing that these cubes information are done.
**Move to Review when:**
**Move to Closed when:** After send the mail

**Comment by mralmanzar** [comment]
All information was created on MARLO and sent to the dashboard.
![image](https://user-images.githubusercontent.com/9383649/66072536-da8b8d80-e51a-11e9-9580-5b3cddd7cdae.png)
![image](https://user-images.githubusercontent.com/9383649/66072573-e8d9a980-e51a-11e9-8d2c-541258eeb1b5.png)
![image](https://user-images.githubusercontent.com/9383649/66072627-03138780-e51b-11e9-8d98-1c69251d0d28.png)
Was sent the mail to Tania.
![image](https://user-images.githubusercontent.com/9383649/66072740-3ce48e00-e51b-11e9-9b9f-6fa667e7d5e7.png)
