### ISSUE TITLE
[GM] (Clarisa) Modify Milestone & Outcome (Table 5)

### ISSUE THREAD

**Issue by gcmartinezg** [CCAFS/MARLO#2065]
Milestone & Outcome.

- [x] Update structure of Sub-Idos for both Milestone and Outcome
- [x] Find Milestone & Outcome by SMO code rather than DB id.
- [x] Add a year parameter to find Milestone or Outcome.

**Deliverable:** _Clarisa_ functionality
**Move to Review when:** Funtionality will be implemented on _Clarisa Dev_
**Move to Closed when:** Funtionality will be implemented on _Doppler_

**Comment by gcmartinezg** [comment]
@yeyo2k3 [finished](https://github.com/CCAFS/MARLO/commit/04255bf12e72695b9bd876e105cdd1a6a7da438c)

**Comment by gcmartinezg** [comment]
Closed, as discussed with @yeyo2k3
