### ISSUE TITLE
[MA] (Result dashboard) Include AR2017 progress towards milestones to cube

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#2148]
Analyze and include the information of 2017 milestones in the Cube

- [x] Analyze the information
- [x] Include the information in a separate table
- [x] Add the new info into the actual milestones cube.

**Deliverable: Information updated in snowflake**
**Move to Closed when: Mail is sent to Tania and Porsha**

**Comment by mralmanzar** [comment]
The ETLs were updated including the information from a new table with the AR2017 info.
![image](https://user-images.githubusercontent.com/9383649/87426935-9ea34f80-c5a5-11ea-81fe-2eed540f350e.png)

**Comment by mralmanzar** [comment]
We are waiting for answer from the CRPs about some wrong statuses

**Comment by mralmanzar** [comment]
All data is ready and sent to snowflake.

**Comment by mralmanzar** [comment]
![image](https://user-images.githubusercontent.com/9383649/88060517-fef93a80-cb2b-11ea-96b9-6e2a9122818b.png)
