### ISSUE TITLE
[GM] (KDS) Improve the service cgspace-reader.jar

### ISSUE THREAD

**Issue by gcmartinezg** [CCAFS/MARLO#2151]
### Improve the service cgspace-reader.jar

_past issue [here](https://github.com/CCAFS/MARLO/issues/2112)_

### Tasks
- [ ] Documentation / User guide
- [ ] Being able to read from an excel file
- [ ] Being able to extract the handles from an excel column
- [ ] Being able to get the information from a single handle easily
- [ ] Bug fixes

### Look into...
- [ ] Knowing how many of the visits a handle has are between the date range selected

**Move to Review when:** Development finished
**Move to Closed when:** Testing and documentation finished
