### ISSUE TITLE
[GM] (MARLO) Create summaries for the Impact Pathways section

### ISSUE THREAD

**Issue by gcmartinezg** [CCAFS/MARLO#2179]
**We currently do not have reports for the Impact Pathways in MARLO**

The Impact Pathways in MARLO is composed of two sections: Outcomes and Cluster of Activities ([see screenshot](https://www.screencast.com/t/mPIntSOJe8x)).

- [x] Report for Outcomes
- [x] Report for Cluster of Activities (CoA)

### General requirements
- The reports should have the logo of the CRP of the user who wants to generate it.
- If a field is null or empty, it should be replaced by **<Not provided>**

### Requirements for the Outcomes report
- The document should have 2 sheets, one for the outcome's info and one for the milestone's
- The name of the document should be like ImpactPathways-Outcomes-**CRP_NAME**-**PHASE_NAME+YEAR**_**GENERATION_DATE**, where **CRP_NAME** is the CRP of the user who wants to generate the report; **PHASE_NAME+YEAR** is the phase name followed by the year (e.g. AR2019, POWB2020, Upkeep2018, etc); **GENERATION_DATE** is the generation date, formatted like yyyyMMdd-HHmm.

**Outcomes sheet**
The outcomes sheet should list the following fields:
1. Composed id
2. Description
3. Target year
4. Target unit with its target value.
5. The flagship/module with which the outcome is associated with.

**Milestones sheet**
The milestones sheet should list the following fields:
1. Outcome's composed id
2. Outcome's description
3. Milestone's composed id
4. Milestone's title
5. Milestone's target year. **Note:** if the milestone was extended, it should say **TARGET_YEAR** extended to **NEW_TARGET_YEAR** (e.g. 2018 extended to 2019)
6. Status
7. The projects to which the milestone is linked with. **Note:** show only the project id, preceded by the letter P (e.g. P35, P554, P87)
8. Milestone's Target value
9. Level of change
10. Assessment of risk
11. Main risk (**only** if 10 _is not_ **Low**)
12. Other risk (**only** if 11 is **7. Other**)
13. Means of verification
14. Cross-cutting markers (Gender, Youth, Capdev, Climate change)

### Requirements for the Cluster of Activities report
- The document should have 1 sheet, where all the information should be.
- The name of the document should be like ImpactPathways-ClusterOfActivities-**CRP_NAME**-**PHASE_NAME+YEAR**_**GENERATION_DATE**, where **CRP_NAME** is the CRP of the user who wants to generate the report; **PHASE_NAME+YEAR** is the phase name followed by the year (e.g. AR2019, POWB2020, Upkeep2018, etc); **GENERATION_DATE** is the generation date, formatted like yyyyMMdd-HHmm.

**Content**
The sheet should list the following fields:
1. The flagship/module with which the CoA is associated with.
2. CoA identifier
3. CoA title
4. CoA leader(s), formatted like: _last-name, first-name (new line) <mail>_  **Note:** If multiple, they should be separated by a semicolon (e.g Lottin, Edd <e.lottin@ci fa.fr>; González, Felipe<f.gonzalez@us d.org>)
5. Key output statement
6. Contribution (percent) of the statement to the CoA
7. Outcome id
8. Outcome description

### Resources
- An example of how the outcomes report could look like ([click here](https://cgiar.sharepoint.com/:x:/s/CCAFS-KDS/EYSaZ23cIKJNjho_jHmgSZYB7nhtU1S3Smp7ad1cUpSPGA?e=4eZ1nx))
- An example of how the cluster of activities report could look like ([click here](https://cgiar.sharepoint.com/:x:/s/CCAFS-KDS/EdxyRhjkEUNOov32gl4iCp0BT9JVaSEO6fs4ELD1oamQWw?e=rNfJOm))
- A visual representation (in MARLO) of the DB tables to be used for the Outcomes&Milestones report ([screenshot 1](https://www.screencast.com/t/Ck7p1WvlZL)) ([screenshot 2](https://www.screencast.com/t/uYKGjYHVrvRf))
- A visual representation (in MARLO) of the DB tables to be used for the Cluster of Activities report ([screenshot 1](https://www.screencast.com/t/gt8RHvKg)) ([screenshot 2](https://www.screencast.com/t/FcQXIiRmW))
- An example of where the reports should be generated from ([click here](https://www.screencast.com/t/MXIFZ5CUeRq))

**Move to Review when:** The reports are designed
**Move to Closed when:** The reports are ready to be generated in MARLO

**Comment by gcmartinezg** [comment]
Added Cluster of Activities (CoA) report

**Comment by MargaritaRamirez** [comment]
@gcmartinezg There is a comment for CoA report I will review the milestones and outcomes 
- [x] Generation date
- [x] Logo from the CRP 
- [x] The flagship/module with which the CoA is associated with
- [x] Cluster identifier
- [ ] ![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/561255a9-81b5-48c5-9acf-52d7eefcd8ed)
- [x] CoA leader(s), formatted like: last-name, first-name (new line) Note: If multiple, they should be separated by a semicolon (e.g Lottin, Edd <e.lottin@ci fa.fr>; González, Felipe<f.gonzalez@us d.org>)
- [x] Key output statement
- [x] Contribution (percent) of the statement to the CoA
- [x] Outcome id
- [x] Outcome description

**Comment by MargaritaRamirez** [comment]
Milestones sheet reviewing process 

- [x] Outcome's composed id
- [x] Outcome's description
- [x] Milestone's composed id
- [x] Milestone's title
- [ ] Milestone's target year. Note: if the milestone was extended, it should say TARGET_YEAR extended to NEW_TARGET_YEAR (e.g. 2018 extended to 2019)
- [x] Status
- [x] The projects to which the milestone is linked with. Note: show only the project id, preceded by the letter P (e.g. P35, P554, P87)
- [x] Milestone's Target value
- [x] Level of change
- [x] Assessment of risk
- [x] Main risk (only if 10 is not Low)
- [ ] Other risk (only if 11 is 7. Other)
- [x] Means of verification
- [x] Cross-cutting markers (Gender, Youth, Capdev, Climate change)

**Comment by MargaritaRamirez** [comment]
Outcomes sheet reviewing process 

- [x] Composed id
- [x] Description
- [x] Target year
- [x] Target unit with its target value.
- [x] The flagship/module with which the outcome is associated

**Comment by MargaritaRamirez** [comment]
General comments: 
- Merge cells 
* outcome sheet ![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/4a20243a-d43a-48e7-9d09-dd29742c33c7)
* Milestones sheet ![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/ff51612a-dbc7-450a-b7ac-a01e619c8826)
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/3d08c856-8267-4a3f-8e36-a1a36fb45278)
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/79f54c04-988b-4418-9be3-4d8fc52f7838)
* CoA  ![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/9b2b5cb7-0e4d-4ed2-b3fa-358d600a76c2)
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/82d55869-7828-4d47-b897-2dace0e7b847)

**Comment by mralmanzar** [comment]
### OUTCOMES SHEET
Data is ok.
- Put allways the principal subido first
![image](https://user-images.githubusercontent.com/9383649/133690168-4334841b-f2f6-45f4-b523-92a9e806aa40.png)
- In the outcomes include a legend explaining that the * marks the principal subido.
### MILESTONES
Data is ok
- Add the FP as first column
### Cluster of activities Sheet
Data is ok
- Change the column name
![image](https://user-images.githubusercontent.com/9383649/133693981-4e141501-e3e5-44fb-8411-9ceb66df3ce7.png)

**Comment by MargaritaRamirez** [comment]
A4NH review
- [ ] Outcome sheet
- [ ] Milestone sheet
- [ ] CoA

All the information reflects (I selected random flagships to review the information)

**Comment by gcmartinezg** [comment]
This development is already in PROD.
