### ISSUE TITLE
[KT] (AICCRA) Fix Outcomes (Indicators), Milestones and project relations replications and save

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2257]
Fix replication and save of:

- [ ] Progress to targets indicators (Baseline indicators) at impact pathway
- [x] Progress to targets indicators (Baseline indicators) at project level
- [x] Contribution to performance indicators

**Comment by MargaritaRamirez** [comment]
The dropdown list of performance indicator matches the information.
