### ISSUE TITLE
[GM-VV] (MARLO) QA Adjustments for Table 5 (Outcomes & Milestones)

### ISSUE THREAD

**Issue by valviveros** [CCAFS/MARLO#2360]
QA Adjustments for Table 5 (Outcomes & Milestones)

- [x] Evidence link - Update to Mandatory if status is "Changed" & Optional if status is "Cancelled" OR "Extended".
- [x] Cross-cutting markers (Gender, Youth, CapDev, Climate Change) justification mandatory if marked 1.Significant OR 2.Principal.  Justification up to 100 words.
- [x] Links to evidence - Should be limited up to 10.

To see SMO Comments: https://cgiar.sharepoint.com/:x:/s/APR-2020-QAteam/EWw5_gX8ikRAvm-FqnW1J6wBTWxLo3Q51GLydux7lrbVow?e=W2MkQY

**Move to Closed when:** moved to dev.

**Comment by valviveros** [comment]
- [ ] Fix the saving for the Evidence link field.
