### ISSUE TITLE
[MR] (AICCRA) Create the work plan (schedule) for AR2021

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2381]
The report will be delivered to the WB on January 20, 2022

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/948228aa-be4b-4049-897c-5fe2acc08fa2)

- [x] Create the project with the proposed schedule
- [x] Send to hector for review
- [ ] Make the adjustments

**Move to Review when:** Send to Hector
**Move to Closed when:** Have final version
