### ISSUE TITLE
AICCRA - How to manage personal data in the reports

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2436]
Considering that for AICCRA we will manage a lot of capacity development events we need to create a process to inform all our users about the correct way to collect personal data and how to disclose this information.   

- [ ] Review authorization of image use and extract information from it
- [ ] Share with Leroy and David Machado for review
- [ ] Create a template with the standardized information
- [ ] Share the information with all the AICCRA users
